#!/usr/bin/env python3
import json
from pathlib import Path

# List of files that need workspacePath added
files_to_update = [
    'src/pages/gcse/aqa/bio/index.astro',
    'src/pages/gcse/aqa/bio/1/2.astro',
    'src/pages/gcse/aqa/bio/1/3.astro',
    'src/pages/gcse/aqa/bio/2/1.astro',
    'src/pages/gcse/aqa/bio/2/2.astro',
    'src/pages/gcse/aqa/bio/2/3.astro',
    'src/pages/gcse/aqa/bio/3/1.astro',
    'src/pages/gcse/aqa/bio/3/2.astro',
    'src/pages/gcse/aqa/bio/3/3.astro',
    'src/pages/gcse/aqa/bio/4/1.astro',
    'src/pages/gcse/aqa/bio/4/2.astro',
    'src/pages/gcse/aqa/bio/5/1.astro',
    'src/pages/gcse/aqa/bio/5/2.astro',
    'src/pages/gcse/aqa/bio/5/3.astro',
    'src/pages/gcse/aqa/bio/5/4.astro',
    'src/pages/gcse/aqa/bio/6/1.astro',
    'src/pages/gcse/aqa/bio/6/2.astro',
    'src/pages/gcse/aqa/bio/6/3.astro',
    'src/pages/gcse/aqa/bio/7/1.astro',
    'src/pages/gcse/aqa/bio/7/2.astro',
    'src/pages/gcse/aqa/bio/7/3.astro',
    'src/pages/gcse/aqa/bio/7/4.astro',
    'src/pages/gcse/aqa/bio/7/5.astro',
    'src/pages/gcse/aqa/ch/index.astro',
    'src/pages/gcse/aqa/ch/1/1.astro',
    'src/pages/gcse/aqa/ch/1/2.astro',
    'src/pages/gcse/aqa/ch/1/3.astro',
    'src/pages/gcse/aqa/ch/2/1.astro',
    'src/pages/gcse/aqa/ch/2/2.astro',
    'src/pages/gcse/aqa/ch/2/3.astro',
    'src/pages/gcse/aqa/ch/2/4.astro',
    'src/pages/gcse/aqa/ch/3/1.astro',
    'src/pages/gcse/aqa/ch/3/2.astro',
    'src/pages/gcse/aqa/ch/3/3.astro',
    'src/pages/gcse/aqa/ch/3/4.astro',
    'src/pages/gcse/aqa/ch/3/5.astro',
    'src/pages/gcse/aqa/ch/4/1.astro',
    'src/pages/gcse/aqa/ch/4/2.astro',
    'src/pages/gcse/aqa/ch/4/3.astro',
    'src/pages/gcse/aqa/ch/5/1.astro',
    'src/pages/gcse/aqa/ch/5/2.astro',
    'src/pages/gcse/aqa/ch/6/1.astro',
    'src/pages/gcse/aqa/ch/6/2.astro',
    'src/pages/gcse/aqa/ch/7/1.astro',
    'src/pages/gcse/aqa/ch/7/2.astro',
    'src/pages/gcse/aqa/ch/7/3.astro',
    'src/pages/gcse/aqa/ch/7/intro.astro',
    'src/pages/gcse/aqa/ch/8/1.astro',
    'src/pages/gcse/aqa/ch/8/2.astro',
    'src/pages/gcse/aqa/ch/8/3.astro',
    'src/pages/gcse/aqa/ch/9/1.astro',
    'src/pages/gcse/aqa/ch/9/2.astro',
    'src/pages/gcse/aqa/ch/9/3.astro',
    'src/pages/gcse/aqa/ch/10/1.astro',
    'src/pages/gcse/aqa/ch/10/2.astro',
    'src/pages/gcse/aqa/ch/10/3.astro',
    'src/pages/gcse/aqa/ch/10/4.astro',
    'src/pages/gcse/aqa/ph/index.astro',
    'src/pages/gcse/aqa/ph/2/1.astro',
    'src/pages/gcse/aqa/ph/5/1.astro',
    'src/pages/gcse/aqa/ph/5/6.1.astro',
    'src/pages/gcse/aqa/ph/8/1.astro',
    'src/pages/gcse/aqa/ph/8/2.astro',
    'src/pages/gcse/aqa/eng/index.astro',
    'src/pages/gcse/aqa/eng/aic.astro',
    'src/pages/gcse/aqa/eng/jandh.astro',
    'src/pages/gcse/aqa/eng/macbeth.astro',
    'src/pages/gcse/aqa/eng/poetry.astro',
    'src/pages/gcse/aqa/index.astro',
]

print(f"Total files to update: {len(files_to_update)}")
for file_path in files_to_update:
    full_path = Path(file_path)
    status = "EXISTS" if full_path.exists() else "NOT FOUND"
    print(f"  {file_path}: {status}")
